server:
  port: 8080
spring:
  application:
    name: configServer
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:/data/configServer/conf/{application}/{profile}